### ISSUE TITLE
From conda command prompt do these two commands. Just copy and paste and enter to run. It will install the pycocotools. Then you can use the demo files in the repository. Or just use google colab.

### ISSUE THREAD

**Issue by tirthraj13** [pdollar/coco#398]
(base) C:\Users\tmcde>pip3 install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
Collecting pycocotools
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\tmcde\appdata\local\temp\pip-install-8euzqxwu\pycocotools
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\tmcde\AppData\Local\Temp\pip-install-8euzqxwu\pycocotools'
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\tmcde\AppData\Local\Temp\pip-wheel-snfqqtqb'
       cwd: C:\Users\tmcde\AppData\Local\Temp\pip-install-8euzqxwu\pycocotools\PythonAPI
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.7\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\pycocotools
  creating build\temp.win-amd64-3.7\common
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tmcde\anaconda3\lib\site-packages\numpy\core\include -I../common -Ic:\users\tmcde\anaconda3\include -Ic:\users\tmcde\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
  _mask.c
  c:\users\tmcde\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\tmcde\AppData\Local\Temp\pip-install-8euzqxwu\pycocotools
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\tmcde\AppData\Local\Temp\pip-install-8euzqxwu\pycocotools\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
      aliases=aliases)
    File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 810, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 109, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tmcde\AppData\Local\Temp\pip-record-9h6ofmdn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmcde\anaconda3\Include\pycocotools'
         cwd: C:\Users\tmcde\AppData\Local\Temp\pip-install-8euzqxwu\pycocotools\PythonAPI
    Complete output (9 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tmcde\anaconda3\lib\site-packages\numpy\core\include -I../common -Ic:\users\tmcde\anaconda3\include -Ic:\users\tmcde\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
    _mask.c
    c:\users\tmcde\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-install-8euzqxwu\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tmcde\AppData\Local\Temp\pip-record-9h6ofmdn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmcde\anaconda3\Include\pycocotools' Check the logs for full command output.
------------------------------------------------------------------------------------------------------
i still facing the problem.so,please help me to overcome this issue.please help!!!!!!

**Comment by virafpatrawala** [comment]
If you are working in Conda, you can follow the below steps to be able to install, import and use this library quite smoothly.

```
### Enter the below in your Conda Command Prompt ###
# Create a new environment
conda create -n <envName>
# Activate the environment
conda activate <envName>
# Install cython
pip install cython
# Install git
conda install -c anaconda git
# Install pycocotools from this GitHub rep
pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
```

Additionally, I have recently written an entire post on [exploring and manipulating the COCO dataset](https://towardsdatascience.com/master-the-coco-dataset-for-semantic-image-segmentation-part-1-of-2-732712631047). Do have a look.

**Comment by Luo-Zhongwei** [comment]
> If you are working in Conda, you can follow the below steps to be able to install, import and use this library quite smoothly.
> 
> ```
> ### Enter the below in your Conda Command Prompt ###
> # Create a new environment
> conda create -n <envName>
> # Activate the environment
> conda activate <envName>
> # Install cython
> pip install cython
> # Install git
> conda install -c anaconda git
> # Install pycocotools from this GitHub rep
> pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
> ```
> 
> Additionally, I have recently written an entire post on [exploring and manipulating the COCO dataset](https://towardsdatascience.com/master-the-coco-dataset-for-semantic-image-segmentation-part-1-of-2-732712631047). Do have a look.

hi，this  command wont work
【pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI】
