### ISSUE TITLE
Numpy Error

### ISSUE THREAD

**Issue by Adblu** [pdollar/coco#421]
When doing evaluation:

```
annFile = 'ex3_stats.json'
resFile = 'ex3_stats_fakesegm100_results.json'


cocoGt = COCO(annFile)
cocoDt = cocoGt.loadRes(resFile)

annType = 'segm'
cocoEval = COCOeval(cocoGt,cocoDt,annType)
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()

```

I'm getting following error:
```
Traceback (most recent call last):
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/n/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6777d397d745>", line 1, in <module>
    runfile('/home/n/Documents/cars_mask_rcnn/tests/debug3.py', wdir='/home/n/Documents/cars_mask_rcnn/tests')
  File "/snap/pycharm-community/194/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/194/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/n/Documents/cars_mask_rcnn/tests/debug3.py", line 4, in <module>
    iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

**Comment by wenh06** [comment]
Since version 1.18, `np.linspace` would raise error other than warning if its 3rd argument `num` was not an integer. You can check the differences among different branches (versions) of this function [here](https://github.com/numpy/numpy/blob/maintenance/1.18.x/numpy/core/function_base.py). You can try using an older version of numpy via `pip install numpy==1.17.0 -U`

Numpy 1.18 has been released for almost half a year, but the developers of `pycocotools` still leave this 'bug' unfixed....
