### ISSUE TITLE
pycocotools subprocess error 

### ISSUE THREAD

**Issue by SOVEREIGNsc2** [pdollar/coco#571]
i have been trying to install pycocotools but it comes back with this error 

PS C:\Users\mattw\PycharmProjects\Orion_TS> pip install pycocotools --use-pep517
Collecting pycocotools
  Using cached pycocotools-2.0.4.tar.gz (106 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: matplotlib>=2.1.0 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from pycocotools) (3.5.1)
Requirement already satisfied: numpy in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from pycocotools) (1.22.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (4.29.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (9.0.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (3.0.7)
Requirement already satisfied: six>=1.5 in c:\users\mattw\anaconda3\envs\orion_ts\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools) (1.16.0)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
      building 'pycocotools._mask' extension
      Traceback (most recent call last):
        File "C:\Users\mattw\anaconda3\envs\Orion_TS\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\mattw\anaconda3\envs\Orion_TS\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\mattw\anaconda3\envs\Orion_TS\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\build_meta.py", line 214, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 19, in <module>
          setup(
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
          self.initialize()
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-x520118t\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/vi
sual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

**Comment by gunesevitan** [comment]
I have the same problem.

Python: 3.9.10
Pytorch: 1.10
Cuda: 11.3
OS: Ubuntu 20.04.3 LTS

**Edit**: I solved it by installing python3.9-dev. `sudo apt-get install python3.9-dev`

**Comment by SOVEREIGNsc2** [comment]
where did you input that command
