### ISSUE TITLE
no module named _mask?

### ISSUE THREAD

**Issue by dbmlabs** [pdollar/coco#59]
I installed the coco library by doing: 
python setup.py build_ext --inplace

Anybody run into the below error after importing?

ImportErrorTraceback (most recent call last)
<ipython-input-20-5a593b0df792> in <module>()
----> 1 from pycocotools.coco import COCO

/usr/local/lib/python2.7/dist-packages/pycocotools/coco.py in <module>()
     53 import copy
     54 import itertools
---> 55 from . import mask as maskUtils
     56 import os
     57 from collections import defaultdict

/usr/local/lib/python2.7/dist-packages/pycocotools/mask.py in <module>()
      1 __author__ = 'tsungyi'
      2 
----> 3 import pycocotools._mask as _mask
      4 
      5 # Interface for manipulating masks stored in RLE format.

ImportError: No module named _mask

**Comment by JackLongKing** [comment]
I compile PythonAPI with python3.5 meeting the problem, but with python2.7, it successed. I think you should "cd coco/PythonAPI and with make"

**Comment by LeeKyungMoon** [comment]
I'm confronting the exactly same issue on "Windows" , did you solve this problem?

I got an error "pycocotools/_mask.pyx" doesn't match any files when running the command 'make'

**Comment by duanyzhi** [comment]
same queston……

**Comment by ksaluja15** [comment]
1) Go to PythonAPI folder
2) run 'make'

**Comment by LeeKyungMoon** [comment]
@ksaluja15 when following the instruction you suggested, the error occurs especially on windows. People including me are talking about that not about the necessary commands.

**Comment by asylbek27** [comment]
@LeeKyungMoon based on the page "http://coco.lri.fr/COCOdoc/installation.html", Python API requires Python 2.7. 
Since I am also using Python 3.6 with Tensorflow-GPU, I am facing with the same problem. I cannot move to Python 2.7, no Tensorflow-GPU Support on Windows. Whenever you find the solution, could you please let me know too?:)

**Comment by XgDuan** [comment]
When you run `make` under the PythonAPI folder, actually you run the command `python setup.py build_ext --inplace`,  within which your default python(mostly python2) is called. So, just run the command `python3 setup.py build_ext --inplace` in the PythonAPI folder for python3.

**Comment by GzuPark** [comment]
@LeeKyungMoon @asylbek27 Please see here "[https://github.com/philferriere/cocoapi](https://github.com/philferriere/cocoapi)". To summarize, after download api, then run `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`.

**Comment by AVI18794** [comment]
@XgDuan  I am having problem which says
![image](https://user-images.githubusercontent.com/37730987/38291206-3efcde9a-37fc-11e8-8f71-aaa65c86a977.png)
Can you help me in rectifying the error.

**Comment by HarshalGarg** [comment]
https://github.com/philferriere/cocoapi
excellent github link with windows support.
it will solve your problem

**Comment by moyans** [comment]
if you cocoapi make success，you can  cd /your python path/lib/python2.7
ln -s /your cocoapi path/PythonAPI/pycocotools/ .

**Comment by sem-onyalo** [comment]
@XgDuan 's answer solved it for me. I was running (on Windows) `python setup.py build` and `python setup.py install` when I should've been running `python setup.py build_ext --inplace` on the https://github.com/philferriere/cocoapi repo (check Makefile in repo).

**Comment by legnaib** [comment]
I had the same issue, but with the
`python setup.py build_ext --inplace` command I get an error that tells me, that I must install Microsoft Visual C++ 14.0(url)
![screenshot 18](https://user-images.githubusercontent.com/33205794/44714927-caeb7b00-aab6-11e8-9eaa-a9a107833bc2.png)

But after installing the Visual Build Tools, I get this error again.
Can someone help?
So I only changed the error from the missing _mask to the missing visual build tool 😠 But I had the hope to solve this issue 😞 😢

**Comment by Tju-AI** [comment]
> 
> 
> @ksaluja15 when following the instruction you suggested, the error occurs especially on windows. People including me are talking about that, not about the necessary commands.

same question,have you solved it?

**Comment by Tju-AI** [comment]
> 
> 
> @leekyungmoon based on the page "http://coco.lri.fr/COCOdoc/installation.html", Python API requires Python 2.7.
> Since I am also using Python 3.6 with Tensorflow-GPU, I am facing with the same problem. I cannot move to Python 2.7, no Tensorflow-GPU Support on Windows. Whenever you find the solution, could you please let me know too?:)

same question,have you solved it?

**Comment by smehta12** [comment]
I followed the instructions https://github.com/philferriere/cocoapi including installation of the Visual Studio Build Tools 2015 for Windows. But it is running into the same issue--->ModuleNotFoundError: No module named 'pycocotools._mask'

My python version is 3.6.5.

**Comment by dem123456789** [comment]
cite from

**Comment by russelldj** [comment]
The above worked for me with Ubuntu 16 and python 3.6.7 under conda. I'm not sure why, but it might be something about the relative imports. This was my previous error in case it is at all useful: 
`>>> from cocoapi.PythonAPI.pycocotools import mask as Mask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr0/home/drussel1/dev/handtracking/deep_sort/deep_sort/cocoapi/PythonAPI/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools'`

**Comment by Minxiangliu** [comment]
@GzuPark I try to run `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`
or run `coco\PythonAPI python setup.py build_ext install` in Windows10(Python3.5/Anaconda4.5). I am get the same error. Do you have any suggestions?
error message:
```
D:\cocoapi-master\cocoapi-master\PythonAPI>python setup.py build_ext install
running build_ext
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    ext_modules= ext_modules
  File "C:\Users\stust\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\stust\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\stust\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\stust\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\stust\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\stust\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\stust\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "C:\Users\stust\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Users\stust\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Users\stust\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()
```

**Comment by vyviansomaya** [comment]
It still fails for me. these are the following steps I took

$ git clone https://github.com/pdollar/coco.git
$ cd coco/PythonAPI
$ make
$python setup.py install

I open a new notebook in AWS SageMaker in the PythonAPI directory and tried to import pycocotools, it succeeded.
Next, I tried "from pycocotools.coco import COCO" and got the "No module named _mask" output. I have done everything in the comments above and I still fail. The only difference I notice is that I'm using SageMaker . should that be the issue? or if its something else please let me know!

@dem123456789 I tried moving it to different directories too. which directory did you use that it started working?

**Comment by EMCP** [comment]
@vyviansomaya , I succeeded using COCO in another project by running the latest github master branch, then moving the entire `/pycocotools` into an area that seemed to be where the old version was 

The legacy location that was not working @ 
`https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0/lib/pycocotools`

then I failed to run because the COCOAPI wasn't working see https://github.com/jwyang/faster-rcnn.pytorch/issues/410#issuecomment-469852281

I made a move with this
```
faster-rcnn.pytorch/lib$ rm -rf pycocotools/
faster-rcnn.pytorch/lib$ mv <PATH_TO_FRESH_GIT_CLONE>/cocoapi/PythonAPI/pycocotools .
```

**Comment by Inmgjim** [comment]
@EMCP , I also succeeded using CUDA=10 on 2080 TI. 
faster-rcnn.pytorch/lib$ rm -rf pycocotools/
faster-rcnn.pytorch/lib$ mv <PATH_TO_FRESH_GIT_CLONE>/cocoapi/PythonAPI/pycocotools
edit Makefile if using python3
than make  pycocotools alone
for solving: 
ImportError: cannot import name '_mask' #410

**Comment by AhmadShaik** [comment]
@XgDuan  Thank you. Your solution perfectly worked for me.

**Comment by kangkang59812** [comment]
@EMCP totally correct! It confused me a few days.

**Comment by ankit204** [comment]
Thanks @XgDuan. That works for me too!

**Comment by koenie64** [comment]
Obvisously missing a step; while trying to run 'Make' I'll continiously get the error 'recipe for target 'all'  failed'

**Comment by icmpnorequest** [comment]
@XgDuan I have already tried `python3 setup.py build_ext --inplace` to Make under cocoapi/PythonAPI, and it doesn't show any errors. 

OS: Ubuntu 18.04 LTS
Python Version = 3.6.8 (System Default Version)

However, When I run the command line:
```
$ python object_detection/model_main.py --pipeline_config_path=pretrained/pipeline.config --model_dir=train --num_train_steps=1000 --sample_1_of_n_eval_examples=1 --alsologtostderr
```

It shows the error again.
```
Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/model_lib.py", line 28, in <module>
    from object_detection import eval_util
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/eval_util.py", line 28, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "/home/yantong/PycharmProjects/PedestrianDetection/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/yantong/PycharmProjects/PedestrianDetection/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'
```

Do you know how to fix this issue? Thanks in advance.

**Comment by Smartdevice2ai** [comment]
On Windows Cocoapi failed to build:-
Please Provide me the way to solve this.
(venv_obj_gpu2) C:\ML_DEV\Tensorflow_obj_det_api2\models\research>pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
Collecting pycocotools from git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\subham\appdata\local\temp\pip-install-iiem7z7n\pycocotools
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\subham\AppData\Local\Temp\pip-install-iiem7z7n\pycocotools'
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\subham\\AppData\\Local\\Temp\\pip-install-iiem7z7n\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\subham\\AppData\\Local\\Temp\\pip-install-iiem7z7n\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\subham\AppData\Local\Temp\pip-wheel-r4ac63g1' --python-tag cp36
       cwd: C:\Users\subham\AppData\Local\Temp\pip-install-iiem7z7n\pycocotools\PythonAPI
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\pycocotools
  creating build\temp.win-amd64-3.6\common
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\numpy\core\include -I../common -IC:\ProgramData\Anaconda3\envs\venv_obj_gpu2\include -IC:\ProgramData\Anaconda3\envs\venv_obj_gpu2\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.6\Release\pycocotools/_mask.obj
  _mask.c
  c:\programdata\anaconda3\envs\venv_obj_gpu2\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  pycocotools/_mask.c(3277): warning C4244: '=': conversion from 'Py_ssize_t' to 'siz', possible loss of data
  pycocotools/_mask.c(3681): warning C4244: 'function': conversion from 'npy_intp' to 'siz', possible loss of data
  pycocotools/_mask.c(6643): warning C4244: '=': conversion from 'npy_intp' to 'siz', possible loss of data
  pycocotools/_mask.c(7389): warning C4244: '=': conversion from 'Py_ssize_t' to 'siz', possible loss of data
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\numpy\core\include -I../common -IC:\ProgramData\Anaconda3\envs\venv_obj_gpu2\include -IC:\ProgramData\Anaconda3\envs\venv_obj_gpu2\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.6\Release\../common/maskApi.obj
  maskApi.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\libs /LIBPATH:C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit__mask build\temp.win-amd64-3.6\Release\pycocotools/_mask.obj build\temp.win-amd64-3.6\Release\../common/maskApi.obj /OUT:build\lib.win-amd64-3.6\pycocotools\_mask.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\pycocotools\_mask.cp36-win_amd64.lib
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\subham\\AppData\\Local\\Temp\\pip-install-iiem7z7n\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\subham\\AppData\\Local\\Temp\\pip-install-iiem7z7n\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\subham\AppData\Local\Temp\pip-install-iiem7z7n\pycocotools
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\subham\AppData\Local\Temp\pip-install-iiem7z7n\pycocotools\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
      aliases=aliases)
    File "C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\Cython\Build\Dependencies.py", line 810, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\Cython\Build\Dependencies.py", line 109, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools

**Comment by swatig1998** [comment]
If you look inside the model/research/ folder, you will find a folder with the name pycocotools. Rename it to any other name. The reason for this problem is that the code imports the pycocotools from this folder, not from the installed folder that you installed the COCO API.

**Comment by khan958** [comment]
> 1. Go to PythonAPI folder
> 2. run 'make'
How can we run 'make' ?

**Comment by rpfly3** [comment]
> faster-rcnn.pytorch/lib$ rm -rf pycocotools/

Before building the api, one more thing is installing cython.

**Comment by wtliao** [comment]
@khan958 
Some people contributes the modified cocoapi[https://github.com/wtliao/coco-caption](url) that supports both py2 and py3.

**Comment by hdh112** [comment]
@XgDuan Thank you so much!

**Comment by zz2summer** [comment]
> When you run `make` under the PythonAPI folder, actually you run the command `python setup.py build_ext --inplace`, within which your default python(mostly python2) is called. So, just run the command `python3 setup.py build_ext --inplace` in the PythonAPI folder for python3. @asylbek27

I solved my problem by this way, thank you.

**Comment by Jackerho** [comment]
error: Don't know how to compile pycocotools/_mask.pyx
help me!!

**Comment by chenjie04** [comment]
> cite from https://github.com/philferriere/cocoapi
> 
> > It happens because there is a pycocotools directory in the same folder as the notebooks. The python code being imported then is the local implementation of pycocotools, not the one installed with pip. To fix this issue, the demo notebooks have been moved to their own directory.
> 
> Basically, I move the demo notebook to another folder and it works.

It is worked for me. Thank you!

**Comment by lxdo517** [comment]
> @XgDuan I am having problem which says
> ![image](https://user-images.githubusercontent.com/37730987/38291206-3efcde9a-37fc-11e8-8f71-aaa65c86a977.png)
> Can you help me in rectifying the error.



> @XgDuan I am having problem which says
> ![image](https://user-images.githubusercontent.com/37730987/38291206-3efcde9a-37fc-11e8-8f71-aaa65c86a977.png)
> Can you help me in rectifying the error.

您的问题最终是怎么解决的啊
