### ISSUE TITLE
ERROR: Failed cleaning build dir for pycocotools

### ISSUE THREAD

**Issue by Robotatron** [pdollar/coco#605]
Doing `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`
gives an error:

```
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\sergiy.shebotnov\appdata\local\temp\pip-req-build-6_5j0eos
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Sergiy.Shebotnov\AppData\Local\Temp\pip-req-build-6_5j0eos'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
      running build_ext
      building 'pycocotools._mask' extension
      creating build\temp.win-amd64-3.8
      creating build\temp.win-amd64-3.8\common
      creating build\temp.win-amd64-3.8\Release
      creating build\temp.win-amd64-3.8\Release\pycocotools
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
      maskApi.c
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
      _mask.c
      c:\users\sergiy.shebotnov\miniconda3\envs\mmdet\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sergiy.Shebotnov\AppData\Local\Temp\pip-req-build-6_5j0eos\PythonAPI\setup.py", line 25, in <module>
          cythonize(ext_modules)
        File "C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pycocotools/_mask.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pycocotools did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'pycocotools._mask' extension
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
      maskApi.c
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
      _mask.c
      c:\users\sergiy.shebotnov\miniconda3\envs\mmdet\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by umepy** [comment]
Same

**Comment by HB-X** [comment]
Same
