### ISSUE TITLE
AttributeError: 'module' object has no attribute 'iou'

### ISSUE THREAD

**Issue by NX-01** [pdollar/coco#65]
Hi,
When import as from demo "pycocotools"
"from pycocotools.coco import COCO"

I get this error:

from pycocotools.coco import COCO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "pycocotools/mask.py", line 76, in <module>
    iou         = _mask.iou
AttributeError: 'module' object has no attribute 'iou'

How can anyone help me?
Python version 2.7

regards

**Comment by tylin** [comment]
It sounds you don't have mask api installed. Please install mask api through running "make" under coco/PythonAPI.

**Comment by samanthawyf** [comment]
Hi, I have the same problem. Could you tell me how to solve it?
