### ISSUE TITLE
There are not annotations for some image ids in MSCOCO?

### ISSUE THREAD

**Issue by mohammad-py** [pdollar/coco#76]
Hi,
I have wrote bellow code:
```

%matplotlib inline
import matplotlib.pyplot as plt
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import numpy as np
import skimage.io as io
import pylab
pylab.rcParams['figure.figsize'] = (10.0, 8.0)

annType = ['segm','bbox','keypoints']
annType = annType[1]      #specify type here
prefix = 'person_keypoints' if annType=='keypoints' else 'instances'
print('Running demo for *%s* results.'%(annType))

#initialize COCO ground truth api
dataDir='../../'
dataType='train2014'
annFile = '%s/annotations/%s_%s.json'%(dataDir,prefix,dataType)
cocoGt=COCO(annFile)

ann = cocoGt.getAnnIds(imgIds=262184)
print(ann)
```
But something went wrong. the output of the last print function is an empty list ([]). For sure, I check is there this specific ID in `mscoc` data or not, which the result is here:

`[[{'coco_url': 'http://images.cocodataset.org/train2014/COCO_train2014_000000262184.jpg', 'width': 640, 'flickr_url': 'http://farm5.staticflickr.com/4044/5080713699_5498b0b6bf_z.jpg', 'date_captured': '2013-11-17 14:24:50', 'id': 262184, 'license': 2, 'file_name': 'COCO_train2014_000000262184.jpg', 'height': 481}]]`

Could you please help me what's wrong with dataset? Is it logical or not?

Best.

**Comment by makefile** [comment]
I came across the similiar problem that for some images I can get annotation ids by using `annIds = coco.getAnnIds(imgIds=imgId, catIds=catIds, iscrowd=None)`,the result annIds contains 2 very large numbers that seems abnormal,then use `coco.loadAnns(annId)` for the annId return None.

**Comment by nightrome** [comment]
I don't think there is any problem. An image can simply have no COCO object in it.

@mohammad-py: In that [image](http://images.cocodataset.org/train2014/COCO_train2014_000000262184.jpg) there is no COCO object as far as I can tell. And you are right that the annotations are empty.

@makefile: The image ids can take basically any number. I think the convention is that regular annotations have low numbers and crowd annotations are more like 9e12 or so. So that's not an issue. But I'm not sure why loadAnns() would return None. Maybe you can post here the exact parameters?

**Comment by makefile** [comment]
@nightrome example: getAnnIds through params of: `'imgId:', 419863, 'catId:', 1` then get result `'annId:', 900100419863L`,and loadAnns return None. the image is [this](http://images.cocodataset.org/train2014/COCO_train2014_000000419863.jpg) and also like [this](http://images.cocodataset.org/train2014/COCO_train2014_000000570346.jpg).

**Comment by nightrome** [comment]
I actually get a valid annotation with both train2014 and train2017:
```
>> coco.loadAnns(900100419863)
[{u'segmentation': {u'counts': [133997, 6, 632, 10, 625, 16, 622, 19, 620, 21, 618, 22, 617, 23, 612, 29, 609, 31, 608, 32, 607, 33, 607, 32, 607, 33, 607, 33, 607, 33, 607, 33, 607, 33, 607, 32, 608, 32, 608, 31, 609, 30, 611, 28, 612, 28, 613, 26, 616, 23, 619, 21, 620, 19, 621, 18, 623, 16, 626, 14, 628, 11, 629, 10, 631, 9, 632, 7, 633, 6, 635, 4, 638, 2, 109521, 1, 639, 1, 639, 1, 639, 1, 638, 3, 637, 3, 618, 1, 5, 4, 8, 5, 22, 2, 588, 29, 19, 6, 585, 31, 16, 9, 583, 33, 13, 12, 582, 34, 10, 14, 581, 41, 2, 17, 579, 61, 579, 61, 579, 62, 578, 62, 579, 62, 578, 61, 579, 60, 581, 60, 580, 60, 581, 59, 581, 59, 582, 57, 586, 5, 3, 45, 597, 42, 603, 37, 603, 36, 604, 36, 605, 34, 606, 34, 607, 33, 607, 32, 609, 31, 609, 31, 610, 29, 611, 28, 613, 27, 613, 27, 614, 25, 615, 5, 10, 9, 635, 4, 15663], u'size': [640, 482]}, u'area': 2958, u'iscrowd': 1, u'image_id': 419863, u'bbox': [209, 215, 248, 133], u'category_id': 1, u'id': 900100419863}]
```
Edit: 
When I run the same with a long integer (900100419863**L**), I also get None, which is exactly your problem. However, getAnnIds() did not return long integers. Are you maybe using Python3? I just read that they treat long integers differently.

**Comment by makefile** [comment]
@nightrome I'm using python2.7.13 in Anaconda on Windows and the annotation file is `instances_train2014.json`.
I'm still get None using `coco.loadAnns(900100419863)`,while `coco.loadAnns(284647)` get results.
Maybe the reason is that I am using this api on Windows?

**Comment by nightrome** [comment]
@tylin : Any idea why this is?

**Comment by mohammad-py** [comment]
@nightrome. Thanks for your response! I have understood.

**Comment by makefile** [comment]
@nightrome I finally find the reason, in python2.7 on Windows, the code `type(900100419863)` get result `long` and in [coco.py](https://github.com/pdollar/coco/blob/master/PythonAPI/pycocotools/coco.py#L208),the line `elif type(ids) == int` has no consideration of type `long`.
I can get result by using `coco.anns[900100419863L]` directly.
Thanks for your response!

**Comment by ptirupat** [comment]
@nightrome I observed that there are 1021 images in train2017 without annotations. Does this mean all these images have no COCO objects in them and they just have the background?

**Comment by nightrome** [comment]
That may well be the case. I'm currently travelling, so I can't check. Why dont you take a look at some of the images?

**Comment by ptirupat** [comment]
I have looked at some of them and they are all just background without coco objects.

**Comment by ptirupat** [comment]
@nightrome I have observed that there are some images in the dataset where the segmentations in the ground truth are overlapping. How are these handled while training a network for semantic segmentation?

**Comment by nightrome** [comment]
@ptirupat: I agree that all of these images seem to have no COCO objects. Let's close this thread.
Regarding your second question, if you are interested in Stuff Segmentation, please post the issue at [https://github.com/nightrome/cocoapi](https://github.com/nightrome/cocoapi). If you mean the segmentation part of COCO detection, then the answer is simply that that is per-instance segmentation, so each instance is treated separately.

**Comment by dexter1608** [comment]
https://github.com/cocodataset/cocoapi/issues/111 any suggestions?
thank you

**Comment by abiller** [comment]
Hello @nightrome. Just discovered the "no coco objects" issue while browsing. Was there any conclusion to this?
It seems to me that most of the images with no annotations I encounter are street signs, mirrors etc. 
http://cocodataset.org/#explore?id=79362

**Comment by nightrome** [comment]
No, street sign and mirror are both not used in COCO. There were 91 classes initially, but 11 classes were removed for whatever reasons. Take a look at the icons here. Those 80 classes are all still used: http://cocodataset.org/#explore?id=79362
Note that stop sign is a different class that still exists. Apart from that, obviously any dataset will have some missing labels, but there is nothing wrong if a few images don't have any labels.

**Comment by GustavZ** [comment]
@nightrome this is very interesting! I was always wondering why there are 80 Classes in COCO but 90 Class IDs (some numbers were missing) and this explains it. Do you know in which year those classes got removed?

I also got a question about how to train on COCO with Tensorflows Object_Detection API, maybe you are also familiar with that:

When training a new model you need to set the num_classes variable in the config. Default for COCO is 90, although there are only 80 classes in it. The label_map TF uses also contains 80 entries, but the IDs go up till 90, same as COCO obviously.
And here is the crux: the num_classes variable defines the spatial size of one dimenson of all convolutional filters, so if you set it to 90 but only use 80 classes you got 10 redundant dimensions.

The Problem is that the num_classes variable also sets the highest valid class_id. Therefore i dont know how i can train only a selected number of classes.
Lets say i want to train on the first ten class_ids and on the last (90th: toothbrush) then i still have to set the num_classes variable to 90 or the 90th id wont get added.

This is major confusing and i have no idea how to work around this problem.
It would be awesome if you have some deeper knowledge about this and can let me know!

Here is the link to some necessary files:
label_map_util where num_classes is used: https://github.com/tensorflow/models/blob/master/research/object_detection/utils/label_map_util.py
coco label_map with 90 ids but 80 classes: https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt
Faster RCNN MetaArch where num_classes is used for spatial size: https://github.com/tensorflow/models/blob/master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py

**Comment by nightrome** [comment]
>Do you know in which year those classes got removed?

They were removed before any data was published.

I don't know how to help you with your Tensorflow problem, but I know that the same issue occurs in Caffe. Usually you can just use a network that outputs all classes even if some don't occur during training. But obviously that requires unnecessary RAM.

**Comment by jinfagang** [comment]
I got also some empty box when training object detection on coco:

```
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000315110.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000097785.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000445775.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000577748.jpg
35500/82783
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000053733.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000316091.jpg
36000/82783
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000185437.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000447701.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000578819.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000054652.jpg
[]
WARNING!!! empty bbox in image: train2014/COCO_train2014_000000579023.jpg

```

But the problem is, I tried to training a RFCN detector, if gt_boxes were empty, it will got an error:

```
im_size: (600.0, 800.0)
scale: 1.25
height, width: (38, 50)
rpn: gt_boxes.shape (0, 5, 1, 1)
rpn: gt_boxes []
total_anchors 28500
inds_inside 15720
anchors.shape (15720, 4)
Traceback (most recent call last):
  File "tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/detection_model_furnace/tools/../lib/fast_rcnn/train.py", line 209, in train_net
    model_paths = sw.train_model(max_iters)
  File "/detection_model_furnace/tools/../lib/fast_rcnn/train.py", line 150, in train_model
    self.solver.step(1)
  File "/detection_model_furnace/tools/../lib/rpn/anchor_target_layer.py", line 162, in forward
    labels[max_overlaps < cfg.TRAIN.RPN_NEGATIVE_OVERLAP] = 0
TypeError: unorderable types: list() < float()

```


Can not figure out how to solve this.........

**Comment by nirandiw** [comment]
I'm am creating coco annotations.json for my own data from scratch. There are images which does not have the object I want to detect. In that case, for such images should I not bother to append any annotations? In other words should I only append an annotation for an image only is there is a segmentation?

**Comment by Mayurji** [comment]
I have been getting FileNotFound Error for 524 images in train2014, so i have written the script to remove those corrupted images from train2014 and its dependences in other json files.

We can do the same for val2014, if the files are missing in that folder, only the folder names needs to be changed.

https://github.com/Mayurji/Computer-Vision/blob/master/Image_Captioning/missingFile_cocodataset.py

**Comment by bnumaomei** [comment]
@nirandiw Hi, have you know how to solve it ? I have met the same question. In my own dataset, some images which does not have the object. For such images should I still append it but leave empty ?Or as you said?

**Comment by jodumagpi** [comment]
> I'm am creating coco annotations.json for my own data from scratch. There are images which does not have the object I want to detect. In that case, for such images should I not bother to append any annotations? In other words should I only append an annotation for an image only is there is a segmentation?

Hi. How did you go about doing this?

**Comment by forever208** [comment]
> @nightrome I observed that there are 1021 images in train2017 without annotations. Does this mean all these images have no COCO objects in them and they just have the background?
> 
> Here is the list of image IDs
> 
> [262184, 262189, 262284, 262623, 508, 524927, 525020, 1111, 263478, 1472, 250, 526104, 1997, 526292, 264720, 526890, 264886, 265207, 3640, 3692, 3799, 3941, 266091, 401670, 266274, 4308, 266518, 266611, 4481, 4517, 267353, 529578, 268496, 6426, 530783, 268693, 268735, 530894, 268770, 531232, 576354, 269372, 531617, 7625, 7823, 271198, 533896, 9759, 9778, 9809, 10108, 10263, 10420, 10440, 534771, 534918, 273123, 11076, 274233, 536587, 349579, 274957, 13035, 537684, 13466, 275710, 537918, 13789, 276267, 276645, 276731, 539016, 539390, 277329, 15404, 539755, 15830, 540388, 540476, 16689, 278907, 541094, 16903, 279103, 279263, 280413, 542614, 280825, 280879, 281035, 543236, 134236, 281188, 281582, 281939, 544188, 544597, 282586, 20490, 172971, 545006, 283147, 545310, 21166, 21382, 309496, 284128, 22098, 284351, 22456, 22559, 547072, 23017, 547760, 285717, 547903, 23648, 135042, 548171, 24181, 548690, 24499, 549012, 25378, 287822, 288131, 26094, 26266, 550869, 550878, 26767, 289071, 551550, 289943, 552135, 28156, 552776, 28645, 28662, 28806, 291056, 291149, 29056, 553420, 29594, 30175, 292572, 573113, 442078, 555470, 31524, 293671, 293946, 31926, 294370, 294431, 557263, 5500, 557387, 33123, 267680, 33422, 167819, 33442, 33554, 558269, 34089, 297058, 559214, 34985, 559576, 35422, 297667, 297736, 35793, 298190, 36480, 298836, 298840, 561119, 299045, 299371, 299382, 299441, 37854, 300090, 562357, 562582, 38691, 300929, 563076, 39068, 224970, 39475, 564317, 40474, 302945, 40962, 565807, 566025, 303892, 566103, 304036, 42345, 566670, 487702, 567234, 305159, 531488, 305871, 43947, 306477, 568863, 45075, 307264, 569451, 45335, 45668, 570045, 45822, 570207, 46633, 308828, 138859, 571242, 309222, 47396, 309571, 572100, 572546, 572585, 310688, 48546, 573053, 576119, 49255, 139284, 184965, 49725, 311877, 49741, 49883, 574385, 50637, 51652, 576017, 51730, 139695, 314068, 533006, 52726, 379190, 315110, 577748, 53733, 316091, 54652, 317120, 317130, 317575, 55559, 55567, 55776, 318144, 318596, 581087, 28095, 402809, 319749, 57977, 58133, 58554, 59250, 321603, 59476, 59550, 359465, 577949, 315846, 60434, 322887, 61045, 61567, 61575, 272421, 324094, 324460, 62805, 62824, 325125, 325357, 325368, 325690, 10654, 64356, 326613, 326793, 578819, 578852, 65380, 327802, 535233, 65916, 328084, 328098, 579023, 66543, 329462, 579247, 330535, 68715, 68838, 69373, 331600, 69514, 331876, 69911, 70125, 332585, 361323, 333198, 71516, 333841, 71879, 334603, 334642, 465057, 203191, 72912, 72978, 335669, 405483, 335826, 143425, 336777, 336873, 12494, 75083, 75256, 337506, 75426, 75481, 75493, 12641, 338067, 76150, 37458, 76923, 339192, 143995, 339740, 77849, 340119, 340375, 340781, 537397, 78947, 79331, 79362, 79671, 79913, 493956, 342335, 342624, 342998, 343035, 81107, 82388, 344618, 344705, 344730, 82756, 345063, 345155, 83246, 345391, 345711, 346061, 84018, 346615, 84638, 84819, 347007, 276311, 101623, 348853, 86818, 86831, 86836, 349083, 349097, 349352, 87847, 350334, 552870, 430665, 88517, 88768, 529570, 89485, 90026, 90171, 90280, 352564, 160137, 91372, 91492, 91705, 354041, 102729, 92554, 92604, 59211, 93994, 94148, 356673, 356834, 94792, 404696, 103341, 90479, 357948, 321854, 358795, 96809, 96923, 359104, 359184, 359207, 359276, 234649, 359774, 97779, 97785, 98121, 98155, 98268, 98679, 16449, 99010, 99364, 191329, 361774, 361831, 362154, 362257, 362351, 362696, 362881, 362986, 101011, 101073, 29564, 101535, 364158, 148102, 102316, 102899, 279350, 365487, 365631, 103910, 366810, 104829, 104880, 105246, 367537, 367998, 106464, 368750, 368884, 369618, 107585, 498563, 107918, 107941, 370151, 370305, 108169, 192817, 370736, 108697, 371307, 291702, 371863, 109942, 110001, 280532, 542695, 111290, 111813, 375096, 113185, 375363, 375611, 499525, 114624, 376835, 377132, 377234, 115250, 115566, 115654, 378632, 378849, 379037, 379138, 117664, 118615, 119438, 151020, 381842, 381984, 382115, 382333, 120235, 382656, 120683, 121107, 545235, 383450, 64024, 122159, 385265, 123239, 123424, 149215, 386200, 124145, 124240, 386613, 124509, 124780, 124983, 125009, 125084, 125182, 108259, 125997, 126210, 388788, 127104, 195993, 389811, 405815, 128740, 391537, 56695, 129903, 129988, 130192, 392534, 130654, 130712, 393212, 393762, 371482, 371484, 394126, 467050, 132531, 395124, 395185, 133693, 554382, 133885, 396166, 397089, 415714, 397187, 397278, 397287, 135849, 136173, 398454, 136779, 136977, 507195, 285068, 400309, 138486, 401212, 401381, 572025, 139326, 401623, 402386, 140603, 402869, 67163, 140922, 403104, 140974, 403279, 141139, 141316, 403851, 404462, 404871, 405104, 143054, 405459, 405662, 405856, 143780, 405945, 406015, 406217, 109558, 144480, 406677, 406709, 242558, 407030, 199063, 407976, 505003, 243018, 409614, 68295, 409953, 148527, 410743, 148622, 410797, 148703, 149102, 411349, 412704, 150616, 150779, 413090, 413120, 413222, 413232, 112605, 287378, 414089, 414416, 414754, 152732, 152858, 415659, 154349, 416555, 154885, 154924, 417689, 200736, 288137, 156299, 223432, 156606, 419106, 420070, 158614, 159073, 159480, 421673, 421970, 160034, 160298, 423028, 39847, 162020, 424528, 162539, 162768, 424980, 163055, 425263, 425439, 425670, 425933, 464210, 114741, 427094, 164999, 427727, 427992, 428379, 166260, 428495, 166524, 354726, 167118, 429386, 429568, 429691, 115475, 431026, 168905, 431234, 508844, 431692, 169722, 432370, 432373, 432647, 433129, 171082, 433546, 433971, 434129, 435435, 275245, 173685, 436048, 174406, 174902, 175129, 175193, 547047, 176149, 176168, 176193, 176649, 176943, 177014, 440269, 440484, 440771, 179430, 292081, 441788, 441863, 38389, 443294, 181462, 443871, 443941, 444302, 182607, 183617, 445775, 445898, 446452, 446646, 184874, 185437, 447701, 186441, 380651, 449082, 449316, 449546, 187882, 187934, 450098, 450343, 188685, 188832, 451373, 189740, 452652, 452746, 452821, 337653, 453087, 453286, 453348, 453566, 191501, 191661, 192062, 454230, 454827, 192764, 455075, 192974, 193077, 193451, 193631, 193704, 193732, 455882, 181035, 399262, 317283, 194574, 194897, 457219, 195266, 195286, 195595, 458540, 207313, 196701, 267229, 459408, 459590, 197774, 198037, 198514, 201632, 464261, 464296, 252194, 444783, 202848, 15318, 465211, 465218, 203221, 203652, 252406, 514557, 466511, 204435, 466935, 466958, 382191, 468064, 468935, 470672, 208708, 209420, 209630, 209969, 210766, 428399, 473495, 211423, 211439, 211665, 474147, 474398, 212675, 35475, 166596, 554841, 475929, 476113, 254124, 214036, 214461, 215450, 478982, 217005, 217118, 479263, 479316, 217649, 218557, 443735, 220160, 482363, 220527, 429995, 482826, 220739, 220932, 221360, 221618, 221680, 221828, 222157, 222330, 222383, 222757, 124731, 81043, 224136, 483334, 486632, 486769, 224742, 77318, 487399, 487516, 225859, 226128, 226629, 488924, 489343, 387416, 227547, 59953, 227699, 489907, 489914, 7592, 228407, 228415, 228727, 491114, 491482, 435360, 518855, 229782, 229981, 38435, 230639, 230795, 252101, 230968, 231119, 231840, 7721, 494812, 495053, 495235, 532277, 234138, 234981, 234988, 514111, 497257, 235529, 235783, 498239, 498371, 236698, 498969, 498975, 499446, 499697, 237718, 301765, 237860, 500079, 238006, 238141, 500780, 501121, 239505, 239942, 502325, 502479, 240436, 240830, 503200, 241209, 503483, 127626, 241595, 503860, 504025, 242092, 504524, 433616, 504886, 242752, 242969, 505583, 505637, 243625, 505865, 346456, 506066, 244108, 244160, 506714, 244636, 244885, 409890, 507257, 245373, 507686, 245560, 507828, 245810, 246348, 508771, 303287, 509036, 246973, 247177, 509423, 247504, 247624, 509792, 509815, 248464, 522127, 434813, 249977, 391200, 250289, 513111, 25816, 513149, 251107, 251132, 8379, 252122, 260501, 129507, 252996, 25885, 515427, 253435, 253520, 253688, 516490, 516542, 254415, 516777, 95772, 516974, 517366, 252918, 518487, 256655, 257034, 519359, 258108, 520316, 258450, 520737, 521098, 521132, 259439, 522013, 259988, 522527, 260484, 130950, 523581, 218357, 524050]

I found the same problem.

**Comment by nightrome** [comment]
@forever208 I am not responsible for COCO, just COCO-Stuff. 
- As pointed out in https://github.com/cocodataset/cocoapi/issues/76#issuecomment-328454082, many images simply have no relevant objects. You might want to check them manually. 
- Also, https://github.com/cocodataset/cocoapi/issues/76#issuecomment-569483249 reported that some images are corrupted.
- Finally, some annotations may simply be missing, which happens in most dataset.

**Comment by ShoufaChen** [comment]
The images that do not have coco-80 annotations in `val2017` set:

[25593, 41488, 42888, 49091, 58636, 64574, 98497, 101022, 121153, 127135, 173183, 176701, 198915, 200152, 226111, 228771, 240767, 260657, 261796, 267946, 268996, 270386, 278006, 308391, 310622, 312549, 320706, 330554, 344611, 370999, 374727, 382734, 402096, 404601, 447789, 458790, 461275, 476491, 477118, 481404, 502910, 514540, 528977, 536343, 542073, 550939, 556498, 560371]

48 images in total.
